#!/bin/sh

# Invokes the SVN-Notify script to send colorized HTML diff e-mail messages.
# This script expects the svnlook program to be on the PATH and the following
# environment variables to be defined:
# SVN_NOTIFY_HOME (path to SVN-Notify installation)
# TO_ADDRESS (address to which e-mails will be sent)
# FROM_ADDRESS (from address to use for e-mails)

SVN_NOTIFY=$SVN_NOTIFY_HOME/bin/svnnotify

REPOS="$1"
REV="$2"

AUTHOR=`svnlook propget $REPOS svn:author -r$REV --revprop`
LOG_MESSAGE=`svnlook propget $REPOS svn:log -r$REV --revprop`
PREFIX=${LOG_MESSAGE:0:17}

if [ $PREFIX != '<forge-publisher>' ]; then

  SMTP=localhost
  SUBJECT_PREFIX="<$AUTHOR> "

  perl -I$SVN_NOTIFY_HOME/lib $SVN_NOTIFY --repos-path $REPOS --revision $REV \
    --to $TO_ADDRESS --from "$FROM_ADDRESS" --subject-prefix "$SUBJECT_PREFIX" \
    --smtp $SMTP --with-diff --handler HTML::ColorDiff
fi

