svn co https://svn.terracotta.org/repo/forge/enterprise/management-apps/branches/tc-3.7 management-apps
svn co https://svn.terracotta.org/repo/internal/fast-restartable-store/trunk fast-restartable-store
svn co https://svn.terracotta.org/repo/internal/offheap-store/trunk offheap-store
svn co https://svn.terracotta.org/repo/ehcache/branches/ehcache-core-2.6.x ehcache-core
svn co https://svn.terracotta.org/repo/internal/ehcache-enterprise/ehcache-core-ee/branches/ehcache-core-ee-2.6.x ehcache-core-ee
svn co https://svn.terracotta.org/repo/forge/projects/management-core/branches/tc-3.7 management-core
svn co https://svn.terracotta.org/repo/ehcache/branches/management-ehcache-2.6.x management-ehcache
svn co https://svn.terracotta.org/repo/ehcache/branches/management-ehcache-impl-2.6.x management-ehcache-impl
svn co https://svn.terracotta.org/repo/quartz/branches/quartz-2.1.x/quartz quartz
svn co https://svn.terracotta.org/repo/forge/projects/terracotta-ehcache/branches/tc-3.7 terracotta-ehcache 
svn co https://svn.terracotta.org/repo/forge/enterprise/terracotta-ehcache-ee/branches/tc-3.7 terracotta-ehcache-ee
svn co https://svn.terracotta.org/repo/forge/projects/terracotta-quartz/branches/tc-3.7 terracotta-quartz
svn co https://svn.terracotta.org/repo/forge/enterprise/terracotta-quartz-ee/branches/tc-3.7 terracotta-quartz-ee
svn co https://svn.terracotta.org/repo/forge/projects/terracotta-toolkit/branches/tc-3.7.7 terracotta-toolkit
svn co https://svn.terracotta.org/repo/forge/enterprise/terracotta-toolkit-ee/branches/tc-3.7.7 terracotta-toolkit-ee
svn co https://svn.terracotta.org/repo/forge/projects/tim-ehcache/branches/tc-3.7 tim-ehcache
svn co https://svn.terracotta.org/repo/forge/enterprise/tim-ehcache-ee/branches/tc-3.7 tim-ehcache-ee
svn co https://svn.terracotta.org/repo/forge/projects/tim-quartz/branches/tc-3.7 tim-quartz
svn co https://svn.terracotta.org/repo/forge/enterprise/tim-quartz-ee/branches/tc-3.7 tim-quartz-ee
